model:
  cosmos_encoder: "Cosmos-Tokenizer-CI8x8"
  llama_model: "/scratch/users/atacelen/housetour/ckpt/Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/"
  
  use_grad_checkpoint: True
  lora: True
  lora_r: 256
  lora_alpha: 256
  lora_inference_mode: True

  frozen_llama_proj: True

  max_txt_len: 2048
  end_sym: "</s>"
  max_frame_pos: 96 

data:
  vis_root: "/scratch/users/atacelen/Reconstructions3D"
  ann_root: "/scratch/users/atacelen/Reconstructions3D/annotations_q_and_a.json"
  num_video_query_token: 32
  tokenizer_name: "/scratch/users/atacelen/housetour/ckpt/Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/"
  data_type: video
  model_type: "llama_v2"
  sample_type: 'rand'
  max_txt_len: 1536  

preprocess:
  vis_processor:
    eval:
      name: "custom_image_array_processor"
      image_size: [512, 288]
      n_frms: 8