model:
  cosmos_encoder: "Cosmos-Tokenizer-CI8x8"
  llama_model: "/scratch/users/atacelen/housetour/ckpt/Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/"
  
  use_grad_checkpoint: True
  lora: True
  lora_r: 128
  lora_alpha: 128
  lora_inference_mode: False

  frozen_llama_proj: False

  max_txt_len: 2048
  end_sym: "</s>"
  max_frame_pos: 96   

data:
  vis_root: "/scratch/users/atacelen/Reconstructions3D"
  ann_root: "/scratch/users/atacelen/Reconstructions3D/annotations_cleaned_v2.json"
  num_video_query_token: 32
  tokenizer_name: "/scratch/users/atacelen/housetour/ckpt/Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/"
  data_type: video
  model_type: "llama_v2"
  sample_type: 'rand'
  max_txt_len: 1536

train:
  batch_size: 1
  num_workers: 1
  weight_decay: 0.05
  init_lr: 1e-4
  min_lr: 2e-5
  warmup_lr: 1e-6
  use_amp: True
  # iters_per_epoch: #TODO
  log_freq: 50
  accum_grad_iters: 8
  snapshot_path: "ckpt/snapshot.pth"

run:
  output_dir: "/scratch/users/atacelen/Cosmos-Tokenizer/results/"
  max_epochs: 20
  eval_only: False
