 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
    arch: blip2_pretrain
    load_finetuned: False
    pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained.pth"

    # ViT
    vit_model: "ckpt/eva-vit-g/eva_vit_g.pth"
    freeze_vit: False
    drop_path_rate: 0
    use_grad_checkpoint: False
    vit_precision: "fp16"

    # QFormer TODO Parameters to be determined!
    num_query_token: 32
    max_txt_len: 512

    image_size: [512, 288]

data:
    vis_root: "/scratch/users/atacelen/Reconstructions3D"
    ann_root: "/scratch/users/atacelen/Reconstructions3D/multi_image_pretrain_w8.json"
    num_video_query_token: 64
    max_txt_len: 448

train:
  batch_size: 4
  num_workers: 2
  weight_decay: 0.05
  init_lr: 3e-5
  min_lr: 1e-6
  warmup_lr: 1e-6
  use_amp: True
  accum_grad_iters: 1

run:
  output_dir: "/scratch/users/atacelen/housetour/results/"
  max_epochs: 10
